### ISSUE TITLE
dynamic prompts doesn't update its list of wild cards unless the server is restarted

### ISSUE THREAD

**Issue by bobpuffer1** [adieyal/comfyui-dynamicprompts#19] opened 2023-09-05 20:02 UTC
ran into this one today. added a bunch of hair colors to the hair color wild cards. couldn't get random prompts to pick them up until I restarted the server

**Comment by adieyal** [comment] 2023-11-10 22:47
Wildcards are cached for performance reasons - I'll give some thought as to the best way to trigger a cache invalidation.

**Comment by adieyal** [comment] 2023-11-10 22:57
this is actually a duplicate of this issue: https://github.com/adieyal/comfyui-dynamicprompts/issues/4

**Closed by adieyal** 2023-11-10 22:57 UTC
